### ISSUE TITLE
[Feature] Change color on the basis user selection

### ISSUE THREAD

**Issue by Rajkumar-stackcoder** [Bauddhik-Geeks/Python-based-Timer-#3]

**Comment by g7i** [comment]
@Rajkumar-stackcoder I would like provide an option menu above the timer for themes.
Example
![Screenshot from 2021-10-02 14-00-44](https://user-images.githubusercontent.com/46393634/135709350-9d9f653b-0e4b-44f2-85f4-e816bb122d4d.png)

**Comment by Rajkumar-stackcoder** [comment]
> 
> 
> @Rajkumar-stackcoder I would like provide an option menu above the timer for themes. Example ![Screenshot from 2021-10-02 14-00-44](https://user-images.githubusercontent.com/46393634/135709350-9d9f653b-0e4b-44f2-85f4-e816bb122d4d.png)

Good to Go. @g7i
